name: Build and Release Fabric Mod

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Get mod version
        id: get_version
        run: |
          version=$(grep '^mod_version=' gradle.properties | cut -d'=' -f2)
          echo "mod_version=$version" >> $GITHUB_OUTPUT

      - name: Check if release exists
        id: check_release
        uses: actions/github-script@v7
        with:
          script: |
            const version = process.env.VERSION;
            const { data: releases } = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const found = releases.find(r => r.tag_name === `v${version}`);
            if (found) {
              core.setOutput('exists', 'true');
              core.setOutput('release_id', found.id);
              core.setOutput('tag', found.tag_name);
            } else {
              core.setOutput('exists', 'false');
            }
        env:
          VERSION: ${{ steps.get_version.outputs.mod_version }}

      - name: Delete previous release and tag if exists
        if: steps.check_release.outputs.exists == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const release_id = ${{ steps.check_release.outputs.release_id }};
            const tag = ${{ steps.check_release.outputs.tag }};
            // Delete the release
            await github.rest.repos.deleteRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release_id
            });
            // Delete the tag
            try {
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `tags/${tag}`
              });
            } catch (e) {
              // Tag might not exist, ignore error
            }

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.mod_version }}
          name: v${{ steps.get_version.outputs.mod_version }}
          draft: false
          prerelease: false

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.mod_version }}
          files: build/libs/*.jar
